name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master', dependendo do seu repositório

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload `src` folder to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: src  

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2